language: node_js
node_js:
    - stable
branches:
    only:
    - master
script:
    - npm test
    - npm run build
env:
    global:
    - GH_REPO: github.com/${TRAVIS_REPO_SLUG}
    - secure: bq2MKhk9MFdB2eBgIL3Lfv/+Kh2G3GYYAn21BP6nfWuYQMET35l9BWP69fY5d+tnHXNEul66AkfERtmgbYGKDGphCLtD/ZX11d6yl97Mg4Gf7fajSIgxq/W85i87CseXIWPBF611Qnehho1g2YQAPglD5HpfwD0jHqo0QW/BtFDbAo2ywr+nvB9fL6mDSpj7hnw2S12opx7nwhBto8qsiGyEWLT1vsqY0EMXc+0nTVkjSxxb/SQVllNgUtqJT6yOh6amfc8fgSjypa+KzdSw2tdl4enGtVDnK0MODoQOL1RNqPSSWaAUP/yR4b8tSKKsO6lLTbSPafta1W8jil/KW3sPTva8/RdVYXhFdzwzxD29duBgndCuntumbyJf2R9yi91gWKoUJFRO0gSd0CIB9udP+v4Rn3jJs/YNQ9YRrNcpeb1/AAGO32QZ+jf8hjVzp0a6t9T3o6Cp4vHk0X/Vn9LSlhRKlP75nidAzctncACTCuuvp72xXSZEU+vf5ye07vv/1jLt2EXa5r9jur+4VXb3zmkQB0D4Rfq6XvcvY8a68uhVIGxaJiC068Bk43qLarKOgEuqq2HAT4MzLVt6Ao+Z7Z5klYGZ2YFFBYETyhcq3F3KIo91StMEgVnsf7T8h8+WZWo6l4vlppQl36uC1woSbmlhvp1ygYAulpDc7GQ=
after_success:
    - npm run deploy

